spring:
  datasource:
    url: jdbc:mysql://db-mysql:3306/mydb?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring
    password: spring
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      format_sql: true,
    show-sql: true
  profiles:
    include: oauth
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: 'true'