spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include:
      - oauth
      - db
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: 'true'